kdt:
  version: 2.0
  path:
    voucher: voucher_list.csv
    user:
      all: user_allList.csv
      black: user_blackList.csv
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    hiddenmethod:
      filter:
        enabled: true